### PR TITLE
Update: v0.5.0

### PR DESCRIPTION
**Pull request by EmmettJayhart**

### CODE REVIEW

**Comment by sionzee** [comment]
@james7132 can we merge this and release it? It is a support for Bevy 8.

**Comment by urothis** [comment]
Doubled, once this is merged bevy_backroll can be updated as well.

**Comment by EmmettJayhart** [comment]
It _should_ also now pass the CI workflow, although I haven't tested it myself.

**Comment by james7132** [comment]
Thanks for the PR. I've been swamped at work and had zero capacity to handle much open source in the past month. Should be mergeable once CI passes.

**Pull request merged**
