### PR TITLE
Fix incorrect link for steamworks-rs

### PR DESCRIPTION
**Pull request by halotroop2288**
Funny how neither of us spotted this

### CODE REVIEW

**Comment by halotroop2288** [comment]
You can simply drop the merge commit after merging if you'd like to keep the git history clean. It doesn't actually do anything useful, just makes Git happy.

**Comment by james7132** [comment]
This is really hard to review. It'd be ideal if you use a commit based on the current branch instead of this git history.

**Comment by halotroop2288** [comment]
What exactly is hard to review about it? It's 2 lines in 2 effected files. If for some reason your https://github.com/HouraiTeahouse/bevy-steamworks/pull/6/files page isn't showing the same way mine is, you can just view [the commit](https://github.com/HouraiTeahouse/bevy-steamworks/pull/6/commits/6ca97c6d6c7f2efe583e31d172b4f1081c21e41e) instead.
The diverging Git history is due to the previous PR being squash-merged, which merged together 18 of these 20 commits. The 19th is the actual change, and the 20th commit simply makes it possible to merge this PR via GitHub.

**Review by james7132 — APPROVED** [review]
Sorry, the diff before the rebase was several thousand LoC, and it was difficult to tell what was going on. LGTM.

**Pull request merged**
